on:
  workflow_dispatch:

jobs:
  build-server-docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: server
          push: true
          tags: |
            ghcr.io/thuasta/thuai-8-server:prototype
