on:
  release:
    types:
      - published

jobs:
  create-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v2
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}

  build-unity-client:
    needs: create-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - StandaloneOSX
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: client/unity
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2022.3.9f1

      - run: |
          mkdir -p release
          cp CHANGELOG.md COPYING client/unity/README.md release/
          cp -r build/${{ matrix.targetPlatform }}/* release/

      - run: |
          zip -r ../${{ github.event.repository.name }}-client-${{ matrix.targetPlatform }}.zip *
        working-directory: release

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-client-${{ matrix.targetPlatform }}.zip

  # TODO: Build web client

  build-server:
    needs: create-release-notes
    permissions:
      contents: write
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm
          - linux-arm64
          - linux-x64
          - linux-musl-arm
          - linux-musl-arm64
          - linux-musl-x64
          - osx-arm64
          - osx-x64
          - win-arm64
          - win-x64
          - win-x86
        include:
          - runs-on: ubuntu-latest
          - runs-on: macos-latest
            runtime: osx-x64
          - runs-on: macos-latest
            runtime: osx-arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet publish src -c Release -o bin \
          --sc true -r ${{ matrix.runtime }} -p:DebugType=none \
          -p:PublishSingleFile=true
        working-directory: server

      - run: |
          mkdir -p release
          cp CHANGELOG.md COPYING server/README.md release/
          cp -r server/bin/* release/

      - run: |
          zip -r ../${{ github.event.repository.name }}-server-${{ matrix.runtime }}.zip *
        working-directory: release

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-server-${{ matrix.runtime }}.zip

  build-server-docker:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: get-version
        uses: frabert/replace-string-action@v2
        with:
          pattern: '^v'
          string: ${{ github.event.release.tag_name }}
          replace-with: ''

      - uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: |
            ghcr.io/thuasta/thuai-8-server:${{ steps.get-version.outputs.replaced }}
            ghcr.io/thuasta/thuai-8-server:latest

  pack-agent:
    needs: create-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - cpp
          - python
    steps:
      - uses: actions/checkout@v4

      - run: |
          zip -r ../${{ github.event.repository.name }}-agent-${{ matrix.language }}.zip ${{ matrix.language }}
        working-directory: sdk

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-agent-${{ matrix.language }}.zip
